development:
  adapter: mysql2
  database: mongop_development
  reconnect: false
  #encoding: UTF-8
  username: root
  password:
  pool: 5

test:
  adapter: mysql2
  database: mongop_test
  reconnect: false
  #encoding: UTF-8
  username: root
  password:
  pool: 5

staging:
  adapter: mysql2
  database: mongop_staging
  reconnect: false
  encoding: UTF-8
  #username: root
  password:
  pool: 5

production:
  adapter: mysql2
  database: mongop_development
  reconnect: false
  username: root
  password:
  pool: 5
